### ISSUE TITLE
A panic when failing to connect to the socket

### ISSUE THREAD

**Issue by iafan** [raff/godet#23]
When running your example from the README verbatim (apart from wrapping into a `func main()`) on my Mac, I'm getting this:

```
$ go run main.go 
REQUEST: GET /json/list HTTP/1.1
Host: localhost:9222



ERROR: dial tcp [::1]:9222: getsockopt: connection refused REQUEST: "GET /json/list HTTP/1.1\r\nHost: localhost:9222\r\n\r\n"

panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1226ba6]

goroutine 1 [running]:
github.com/raff/godet.(*RemoteDebugger).Close(0x0, 0x0, 0x13f5240)
	/Users/xxxxxxxxxxxx/.go/src/github.com/raff/godet/godet.go:321 +0x26
panic(0x126da60, 0x1422700)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/raff/godet.(*RemoteDebugger).Version(0x0, 0x12ccf58, 0x0, 0x0)
	/Users/xxxxxxxxxxxx/.go/src/github.com/raff/godet/godet.go:505 +0x26
main.main()
	/Users/xxxxxxxxxxxx/Documents/Work/Personal/Go/headless_chrome/main.go:17 +0x8a
exit status 2
```

The error seems to be valid (I guess Chrome needs to be run in a special mode in order to listen on that port), but the program shouldn't panic.

From the trace it seems like that a nil `remote` variable is passed down the `Close()` func, and then the `Lock()` method is called on it in this line: https://github.com/raff/godet/blob/master/godet.go#L321

**Comment by raff** [comment]
well, the problem is the missing error check on godet.Connect (that in case of error returns remote = nil)

While I could be checking the value of the receiver, should I do that in every call ? I don't think I have ever seen any code where object methods check the value of the receiver in order to avoid an error.

But I will update the example to check the error code for godet.Connect.

Regarding to the root cause (not being able to connect to Chrome), try godet/cmd/godet/main.go.
In there I have some code that starts the browser with the correct options (should work on MacOS and Linux, and if your browser is installed in a non standard location you can specify an alternative command to run)

**Comment by iafan** [comment]
I agree that a check in every call is not necessary, and your README changes make sense and encourage proper error checking. So thanks!
