### ISSUE TITLE
closing the connection not working.

### ISSUE THREAD

**Issue by mdaliyan** [raff/godet#33]
This code does not close the connection
```
// disconnect when done
defer remote.Close()
```
I tried to crawl so many pages and as time went on, chrome started to eat a lot of memory. This did't happen when I changed the defer code to this:
```
// disconnect when done
defer func(){ remote.Close() }()
```
Just saying.

**Comment by erikdubbelboer** [comment]
```go
defer remote.Close()
```
and
```go
defer func(){ remote.Close() }()
```
obviously do exactly the same.

What I think if your problem is that you probably don't close the tab godet was using. So you are getting more and more tabs. You have to use [CloseTab](https://godoc.org/github.com/raff/godet#RemoteDebugger.CloseTab) to close the tab after you are done with it. `remote.Close()` just disconnects the session, it doesn't close the tab (as you might later want to reconnect to it).

**Comment by raff** [comment]
Yes, the two defer are exactly the same.
