### ISSUE TITLE
remove github.com/gobs/httpclient dependency

### ISSUE THREAD

**Issue by mattetti** [raff/godet#7]
I'm interested in experimenting with godet and I would really appreciate if the amount of dependencies would be limited. In this case it looks like the net/http client from the std lib would work well and that would result in only 1 external dependency: Gorilla's websocket pkg (which might potentially be replaced by https://godoc.org/golang.org/x/net/websocket but that's a different issue all together).

What do you think?

**Comment by raff** [comment]
I actually started with net/http but switched to use gobs/httpclient (that
is also a package I wrote) because of a lot of boiler plate code that I
would have to rewrite (the reason why I wrote gobs/httpclient in the first
place).

I also started with x/net/websocket and switched to Gorilla websocket
because it looks like the other is not really maintained anymore (they link
to Gorilla as a more stable one) and it has a few kinks that are hard to
overcome (can't get a "full" message if it's larger than the internal
buffer).

-- Raffaele

**Comment by mattetti** [comment]
I see. Well, the library works very well. I have it running in Docker and control the rendering of an angular app => html.

The readme code example is a bit buggy but the actual code example is really useful. I'll publish the Docker image a bit later on if you're interested (it should be super useful for Mac developers to run/test chrome headlessly).

Thanks a for a great lib
